config/routes.rb
Rails.application.routes.draw do


  get 'reports/index'

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'dashboards#setting',  as: :settings
    resources :clients
    resources :assessments
    resources :jobs do
      member do
        post :allocated
      end
    end
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'dashboards#setting',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users
    resources :customers
    resources :locations
    resources :assessment_types
    resources :job_types
    resources :clients do
      member do
        get :jobs
        get :assessments
      end
    end
    resources :assessments
    resources :jobs do
      member do
        post :allocated
      end
    end
    resources :businesses, only: [:update] do
      collection do
        get :profile
        end
      end
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                 :integer          not null, primary key
#  client_id          :integer
#  job_type_id        :integer
#  status             :string
#  visit_number       :integer
#  weekly_visit_total :integer
#  user_id            :integer
#  completed_date     :date
#  notes              :string
#  business_id        :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  completed_by_id    :integer
#

class Job < ApplicationRecord
  STATUS = [
    'Pending',
    'Treated',
    'Out of facility',
    'Hospitalised',
    'Refused when offered treatment',
    'Sick',
    'Facility in outbreak',
    'Allied health professional sick',
    'Not completed'
  ]

  belongs_to :client
  belongs_to :job_type
  belongs_to :user, optional: true
  belongs_to :business
  belongs_to :completed_by, class_name: User::name, optional: true
end

app/models/job_type.rb
# == Schema Information
#
# Table name: job_types
#
#  id                    :integer          not null, primary key
#  name                  :string
#  default_weekly_visits :integer
#  business_id           :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class JobType < ApplicationRecord
  belongs_to :business
  has_many :clients
end

app/controllers/admin/jobs_controller.rb
module Admin
  class JobsController < BaseController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :allocated]
  before_action only: [:index] do
    load_ransack_params('admin_jobs')
  end

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:q] && params[:q][:created_at_gteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_gteq].to_date + 7.days
    end

    @search = current_business.jobs.includes(:job_type, :user).preload(client: :location)
                              .joins(client: :location)
                              .ransack(params[:q])

    @jobs = @search.result.order("locations.name ASC, jobs.visit_number ASC, clients.room ASC")
                          .page(params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_business.jobs.new
  end

  # GET /jobs/1/edit
  def edit
    respond_to do |f|
      f.html
      f.js
    end
  end

  def create
    @job = current_business.jobs.new(job_params)
    if @job.save
      redirect_to admin_jobs_path, notice: "Job has beed created successfully"
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @job.delete
    redirect_to admin_jobs_path, notice: "Job has beed deleted successfully"
  end

  def update
    if @job.update job_params
      redirect_to admin_jobs_path, notice: "Job has beed updated successfully"
    else
      render :edit
    end
  end

  def allocated
    @job.update_attribute :user_id, current_user.id

    redirect_to admin_jobs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_id, :client_id, :job_type_id, :status, :visit_number, :weekly_visit_total, :user_id, :completed_date, :notes, :business_id,:completed_by_id)
    end
  end
end

app/controllers/app/jobs_controller.rb
module App
  class JobsController < BaseController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :allocated]
  before_action only: [:index] do
    load_ransack_params('app_jobs')
  end

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:q] && params[:q][:created_at_gteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_gteq].to_date + 7.days
    end

    @search = current_business.jobs.includes(:job_type, :user).preload(client: :location)
                              .joins(client: :location)
                              .where("locations.id IN (?)", current_user.locations.pluck(:id))
                              .ransack(params[:q])

    @jobs = @search.result.order("locations.name ASC, jobs.visit_number ASC, clients.room ASC")
                          .page(params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_business.jobs.new
  end

  # GET /jobs/1/edit
  def edit
    respond_to do |f|
      f.html
      f.js  
    end
  end

  def create
    @job = current_business.jobs.new(job_params)
    if @job.save
      redirect_to app_jobs_path, notice: "Job has beed created successfully"
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @job.delete
    redirect_to app_jobs_path, notice: "Job has beed deleted successfully"
  end

  def update
    if @job.update job_params
      redirect_to app_jobs_path, notice: "Job has beed updated successfully"
    else
      render :edit
    end
  end

  def allocated
    @job.update_attribute :user_id, current_user.id

    redirect_to app_jobs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_id, :client_id, :job_type_id, :status, :visit_number, :weekly_visit_total, :user_id, :completed_date, :notes, :business_id,
        :completed_by_id)
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for([:admin, @job]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :client, label_method: :full_name %>
    <%= f.association :job_type %>
    <%= f.input :status, collection: ['Pending', 'Treated', 'Out of facility', 'Hospitalised', 'Refused when offered treatment', 'Sick', 'Facility in outbreak', 'Allied health professional sick', 'Not completed'] %>
    <%= f.input :visit_number %>
    <%= f.input :weekly_visit_total %>
    <%= f.association :user, label_method: :full_name %>
    <%= f.input :completed_date, as: :string, input_html: { class: 'datepicker' } %>
    <%= f.input :notes, :as => :text, :input_html => {:rows => 5} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/jobs/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-completed-job">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for([:admin, @job]) do |f| %>
      <%= f.input :completed_by_id, as: :hidden, input_html: { value: current_user.id } %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Job completed</h4>
      </div>
      <div class="modal-body">
          <%= f.input :status, collection: ['Pending', 'Treated', 'Out of facility', 'Hospitalised', 'Refused when offered treatment', 'Sick', 'Facility in outbreak', 'Allied health professional sick', 'Not completed'] %>
          <%= f.input :completed_date, as: :string, input_html: {class: 'datepicker'} %>
          <%= f.input :notes, :as => :text, :input_html => {:rows => 5} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button class="btn btn-primary">Save</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/jobs/edit.js.erb
$('#modal-completed-job').remove();
$('body').append('<%= j render('modal') %>');
$('#modal-completed-job').modal('show');

$('#modal-completed-job .datepicker').bootstrapMaterialDatePicker({
  format: 'MMMM DD YYYY',
  weekStart : 0,
  time: false
});

app/views/admin/jobs/index.html.erb
<div class="box box-default">
  <div class="box-body">
    <%= search_form_for [:admin, @search] do |f| %>
    <div class="row">
      <div class="col-md-2">
        <div class="form-group">
          <label>Location</label>
          <%= f.select :client_location_id_eq,
            options_for_select(location_options_for_select(current_business.locations), @search.client_location_id_cont), {include_blank: 'All'}, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Client</label>
          <%= f.select :client_id_eq,
            options_for_select(current_business.clients.pluck(:full_name, :id), @search.client_id_cont), {include_blank: 'All'}, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Job type</label>
          <%= f.select :job_type_id_eq,
            options_for_select(current_business.job_types.pluck(:name, :id), @search.job_type_id_eq), {include_blank: 'All'}, class: 'form-control' %>

        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Status</label>
          <%= f.select :status_eq, options_for_select(Job::STATUS, @search.status_eq), {include_blank: 'All'}, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Allocated user</label>
          <%= f.select :user_id_eq,
            options_for_select(user_options_for_app(current_business.users.order(:first_name)), @search.user_id_eq), {include_blank: 'All'}, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Completed user</label>
          <%= f.select :completed_by_id_eq, 
            options_for_select(user_options_for_app(current_business.users.order(:first_name)), @search.completed_by_id_eq), {include_blank: 'All'}, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Completed start</label>
          <%= f.search_field :completed_date_gteq, value: @search.completed_date_gteq.try(:strftime, "%B %d %Y"), class: 'datepicker form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Completed end</label>
          <%= f.search_field :completed_date_lteq, value: @search.completed_date_lteq.try(:strftime, "%B %d %Y"), class: 'datepicker form-control' %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label>Week commencing</label>
          <%= f.search_field :created_at_gteq, value: @search.created_at_gteq.try(:strftime, "%B %d %Y"), class: 'datepicker form-control' %>
        </div>
      </div>
      <div class="col-md-12">
        <button class="btn btn-default">Search</button>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="box">
  <div class="box-header">
  <h3 class="box-title">Jobs</h3>
    <div class="box-tools">
      <ul class="pull-right">
        <a href="<%= new_admin_job_path %>" class="btn btn-block btn-default btn-sm">New job</a>
      </ul>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Details</th>
          <th>Room</th>
          <th>Location</th>
          <th>Client</th>
          <th>Job type</th>
          <th>Status</th>
          <th colspan="5"></th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.visit_number %> / <%= job.weekly_visit_total %></td>
            <td><%= job.client&.room %></td>
            <td><%= job.client&.location&.customer&.business_name %> | <%= job.client&.location&.name %></td>
            <td><%= job.client&.full_name %></td>
            <td><%= job.job_type&.name %></td>
            <td><%= job.status %></td>
            <% unless job.user.present? %>
            <td>
              <a href="<%= allocated_admin_job_path(job) %>"data-method="POST">
                Allocate to me
              </a>
            </td>
            <% end %>
            <% if job.completed_date.blank? && job.status.blank? %>
              <td>
                <a href="<%= edit_admin_job_path(job) %>" data-method="GET" data-remote="true">
                  Complete
                </a>
              </td>
            <% end %>
            <td><%= link_to 'Show', admin_job_path(job) %></td>
            <td><%= link_to 'Edit', edit_admin_job_path(job) %></td>
            <td><%= link_to 'Delete', admin_job_path(job), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<div class="box-footer">
  <div class="row">
    <div class="col-sm-6">
      <%= page_entries_info @jobs %>
    </div>
    <div class="col-sm-6">
      <%= paginate @jobs %>
    </div>
  </div>
</div>
</div>

app/views/admin/jobs/show.html.erb
<section class="content">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Customers</h3>
    </div>
    <div class="box-body">

      <p>
        <strong>Client:</strong>
        <%= @job.client&.full_name %>
      </p>

      <p>
        <strong>Job type:</strong>
        <%= @job.job_type&.name %>
      </p>

      <p>
        <strong>Status:</strong>
        <%= @job.status %>
      </p>

      <p>
        <strong>Visit number:</strong>
        <%= @job.visit_number %>
      </p>

      <p>
        <strong>Weekly visit total:</strong>
        <%= @job.weekly_visit_total %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @job.user&.full_name %>
      </p>

      <p>
        <strong>Completed by:</strong>
        <%= @job.completed_by&.full_name %>
      </p>

      <p>
        <strong>Completed date:</strong>
        <%= @job.completed_date.try(:strftime, '%B %d %Y') %>
      </p>

      <p>
        <strong>Notes:</strong>
        <%= @job.notes %>
      </p>

      <%= link_to 'Edit', edit_admin_job_path(@job) %> |
      <%= link_to 'Back', admin_jobs_path %>
    </div>
  </div>
</section>