config/routes.rb
Rails.application.routes.draw do


  get 'reports/index'

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'dashboards#setting',  as: :settings
    resources :clients
    resources :assessments
    resources :jobs do
      member do
        post :allocated
      end
    end
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'dashboards#setting',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users
    resources :customers
    resources :locations
    resources :assessment_types
    resources :job_types
    resources :clients do
      member do
        get :jobs
        get :assessments
      end
    end
    resources :assessments
    resources :jobs do
      member do
        post :allocated
      end
    end
    resources :businesses, only: [:update] do
      collection do
        get :profile
        end
      end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < BaseController

  def index
  end

  def setting
  end

end
end

app/controllers/app/dashboards_controller.rb
class App::DashboardsController < App::BaseController

  def index
  end

  def setting
  end

end

app/views/admin/dashboards/index.html.erb
  <section class="content-header">
    <h1>
      Dashboard
    </h1>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-grey"><i class="fa fa-bar-chart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Jobs this week</span>
            <span class="info-box-number">110</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-grey"><i class="fa fa-bar-chart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Jobs today</span>
            <span class="info-box-number">18</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->

      <!-- fix for small devices only -->
      <div class="clearfix visible-sm-block"></div>

      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-grey"><i class="fa fa-bar-chart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Assessments this week</span>
            <span class="info-box-number">10</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-grey"><i class="fa fa-bar-chart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Assessments today</span>
            <span class="info-box-number">2</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
    <div class="row">
      <div class="col-md-6">
        <div class="nav-tabs-custom">
      <!-- Tabs within a box -->
      <ul class="nav nav-tabs pull-right">
        <li class="pull-left header"><i class="fa fa-inbox"></i> Graph: Jobs</li>
      </ul>
      <div class="tab-content no-padding">
        <!-- Morris chart - Sales -->
        <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"></div>
        <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;"></div>
      </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="nav-tabs-custom">
      <!-- Tabs within a box -->
      <ul class="nav nav-tabs pull-right">
        <li class="pull-left header"><i class="fa fa-inbox"></i> Graph: Assessments</li>
      </ul>
      <div class="tab-content no-padding">
        <!-- Morris chart - Sales -->
        <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"></div>
        <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;"></div>
      </div>
        </div>
      </div>
    </div>
    </section>

app/views/admin/dashboards/setting.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Settings</h3>
        </div>
        <div class="box-body">
          <ul>
            <li><a href="<%= admin_assessment_types_path %>"> Assessment types</a></li>
            <li><a href="<%= profile_admin_businesses_path %>"> Business profile</a></li>
            <li><a href="<%= admin_customers_path %>"> Customers</a></li>
            <li><a href="<%= admin_locations_path %>"> Locations</a></li>
            <li><a href="<%= admin_job_types_path %>"> Job types</a></li>
            <li> <a href="<%= admin_users_path %>">Users</a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>